default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: CodyOnRails_development

test:
  <<: *default
  database: CodyOnRails_test

production:
  <<: *default
  database: CodyOnRails_production
  username: codyonrails
  password: <%= ENV['CODYONRAILS_DATABASE_PASSWORD'] %>
